"""
Seed the database with 100+ real popular movies, studios, and a demo user.
Run directly: python -m backend.scripts.seed_data
"""
from urllib.parse import quote

from sqlalchemy.orm import Session

from backend.models.movie import Movie, Studio
from backend.models.user import User
from backend.services.auth_service import get_password_hash


def _poster(title: str) -> str:
    """Generate a placeholder poster URL from a movie title."""
    return f"https://via.placeholder.com/300x450.png?text={quote(title)}"


# ---------------------------------------------------------------------------
# Studio records
# ---------------------------------------------------------------------------
STUDIOS = [
    {"name": "Marvel Studios", "description": "Marvel Studios produces the Marvel Cinematic Universe films based on Marvel Comics characters.", "founded_year": 1993, "logo_url": None},
    {"name": "Warner Bros.", "description": "Warner Bros. Pictures is one of the Big Five major American film studios.", "founded_year": 1923, "logo_url": None},
    {"name": "Universal Pictures", "description": "Universal Pictures is one of the oldest and most iconic American film studios.", "founded_year": 1912, "logo_url": None},
    {"name": "20th Century Studios", "description": "Formerly 20th Century Fox, a major American film studio now owned by The Walt Disney Company.", "founded_year": 1935, "logo_url": None},
    {"name": "A24", "description": "A24 is an independent entertainment company known for acclaimed and original films.", "founded_year": 2012, "logo_url": None},
    {"name": "Toho", "description": "Toho Co., Ltd. is a Japanese film production and distribution company, famous for Godzilla.", "founded_year": 1932, "logo_url": None},
    {"name": "Pixar", "description": "Pixar Animation Studios is an American CGI animation studio known for pioneering computer-animated films.", "founded_year": 1986, "logo_url": None},
    {"name": "Walt Disney Pictures", "description": "Walt Disney Pictures is a major American film production company and flagship of The Walt Disney Studios.", "founded_year": 1983, "logo_url": None},
    {"name": "Lucasfilm", "description": "Lucasfilm Ltd. is an American film and television production company, creator of Star Wars and Indiana Jones.", "founded_year": 1971, "logo_url": None},
    {"name": "Paramount Pictures", "description": "Paramount Pictures Corporation is one of the Big Five major American film studios.", "founded_year": 1912, "logo_url": None},
    {"name": "Columbia Pictures", "description": "Columbia Pictures Industries, Inc. is an American film production and distribution studio, part of Sony Pictures.", "founded_year": 1924, "logo_url": None},
    {"name": "Lionsgate", "description": "Lionsgate Films is a Canadian-American entertainment company known for the Hunger Games and John Wick franchises.", "founded_year": 1997, "logo_url": None},
    {"name": "New Line Cinema", "description": "New Line Cinema is an American film production studio known for The Lord of the Rings trilogy.", "founded_year": 1967, "logo_url": None},
    {"name": "Studio Ghibli", "description": "Studio Ghibli is a Japanese animation film studio known for critically acclaimed anime films.", "founded_year": 1985, "logo_url": None},
]

# ---------------------------------------------------------------------------
# Movie records – 105 movies total
# ---------------------------------------------------------------------------
MOVIES = [
    # ── Marvel / MCU (15) ──────────────────────────────────────────────────
    {"title": "Iron Man", "year": 2008, "genre": "Action, Adventure, Sci-Fi", "plot": "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil. The film launched the Marvel Cinematic Universe and redefined superhero cinema.", "imdb_rating": 7.9, "runtime": "126 min", "director": "Jon Favreau", "actors": "Robert Downey Jr., Gwyneth Paltrow, Terrence Howard, Jeff Bridges", "studio": "Marvel Studios", "franchise": "MCU", "franchise_order": 1, "imdb_id": "tt0371746"},
    {"title": "The Avengers", "year": 2012, "genre": "Action, Adventure, Sci-Fi", "plot": "Earth's mightiest heroes must come together and learn to fight as a team to stop the mischievous Loki and his alien army from enslaving humanity. A groundbreaking crossover event film.", "imdb_rating": 8.0, "runtime": "143 min", "director": "Joss Whedon", "actors": "Robert Downey Jr., Chris Evans, Scarlett Johansson, Mark Ruffalo", "studio": "Marvel Studios", "franchise": "MCU", "franchise_order": 6, "imdb_id": "tt0848228"},
    {"title": "Guardians of the Galaxy", "year": 2014, "genre": "Action, Adventure, Comedy", "plot": "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe. Features a beloved retro soundtrack and irreverent humor.", "imdb_rating": 8.0, "runtime": "121 min", "director": "James Gunn", "actors": "Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel", "studio": "Marvel Studios", "franchise": "MCU", "franchise_order": 10, "imdb_id": "tt2015381"},
    {"title": "Black Panther", "year": 2018, "genre": "Action, Adventure, Sci-Fi", "plot": "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future. A culturally groundbreaking film that earned Best Picture nominations.", "imdb_rating": 7.3, "runtime": "134 min", "director": "Ryan Coogler", "actors": "Chadwick Boseman, Michael B. Jordan, Lupita Nyong'o, Danai Gurira", "studio": "Marvel Studios", "franchise": "MCU", "franchise_order": 18, "imdb_id": "tt1825683"},
    {"title": "Avengers: Infinity War", "year": 2018, "genre": "Action, Adventure, Sci-Fi", "plot": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation puts an end to the universe. The stakes have never been higher.", "imdb_rating": 8.4, "runtime": "149 min", "director": "Anthony Russo, Joe Russo", "actors": "Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans", "studio": "Marvel Studios", "franchise": "MCU", "franchise_order": 19, "imdb_id": "tt4154756"},
    {"title": "Avengers: Endgame", "year": 2019, "genre": "Action, Adventure, Drama", "plot": "After the devastating events of Infinity War, the remaining Avengers assemble once more to reverse Thanos' actions and restore balance to the universe. An epic culmination of 22 films.", "imdb_rating": 8.4, "runtime": "181 min", "director": "Anthony Russo, Joe Russo", "actors": "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth", "studio": "Marvel Studios", "franchise": "MCU", "franchise_order": 22, "imdb_id": "tt4154796"},
    {"title": "Spider-Man: Homecoming", "year": 2017, "genre": "Action, Adventure, Sci-Fi", "plot": "Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man. He faces the Vulture, who threatens New York City.", "imdb_rating": 7.4, "runtime": "133 min", "director": "Jon Watts", "actors": "Tom Holland, Michael Keaton, Robert Downey Jr., Marisa Tomei", "studio": "Marvel Studios", "franchise": "MCU", "franchise_order": 16, "imdb_id": "tt2250912"},
    {"title": "Thor: Ragnarok", "year": 2017, "genre": "Action, Adventure, Comedy", "plot": "Imprisoned on the planet Sakaar, Thor must race against time to get back to Asgard to stop Ragnarok — the destruction of his homeworld — at the hands of the ruthless Hela.", "imdb_rating": 7.9, "runtime": "130 min", "director": "Taika Waititi", "actors": "Chris Hemsworth, Tom Hiddleston, Cate Blanchett, Mark Ruffalo", "studio": "Marvel Studios", "franchise": "MCU", "franchise_order": 17, "imdb_id": "tt3501632"},
    {"title": "Captain America: The Winter Soldier", "year": 2014, "genre": "Action, Adventure, Sci-Fi", "plot": "As Steve Rogers struggles to embrace his role in the modern world, he teams up with Black Widow to battle a powerful yet shadowy enemy — the Winter Soldier. A politically-charged thriller.", "imdb_rating": 7.7, "runtime": "136 min", "director": "Anthony Russo, Joe Russo", "actors": "Chris Evans, Scarlett Johansson, Sebastian Stan, Samuel L. Jackson", "studio": "Marvel Studios", "franchise": "MCU", "franchise_order": 9, "imdb_id": "tt1843866"},
    {"title": "Doctor Strange", "year": 2016, "genre": "Action, Adventure, Fantasy", "plot": "While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts. He discovers alternate dimensions and must protect reality itself.", "imdb_rating": 7.5, "runtime": "115 min", "director": "Scott Derrickson", "actors": "Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams, Tilda Swinton", "studio": "Marvel Studios", "franchise": "MCU", "franchise_order": 14, "imdb_id": "tt1211837"},
    {"title": "Ant-Man", "year": 2015, "genre": "Action, Adventure, Comedy", "plot": "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero to protect the world.", "imdb_rating": 7.3, "runtime": "117 min", "director": "Peyton Reed", "actors": "Paul Rudd, Michael Douglas, Evangeline Lilly, Corey Stoll", "studio": "Marvel Studios", "franchise": "MCU", "franchise_order": 12, "imdb_id": "tt0478970"},
    {"title": "Captain Marvel", "year": 2019, "genre": "Action, Adventure, Sci-Fi", "plot": "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s with a unique origin story.", "imdb_rating": 6.8, "runtime": "123 min", "director": "Anna Boden, Ryan Fleck", "actors": "Brie Larson, Samuel L. Jackson, Ben Mendelsohn, Jude Law", "studio": "Marvel Studios", "franchise": "MCU", "franchise_order": 21, "imdb_id": "tt4154664"},
    {"title": "Spider-Man: No Way Home", "year": 2021, "genre": "Action, Adventure, Fantasy", "plot": "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, threatening to destroy everything.", "imdb_rating": 8.2, "runtime": "148 min", "director": "Jon Watts", "actors": "Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon", "studio": "Marvel Studios", "franchise": "MCU", "franchise_order": 27, "imdb_id": "tt10872600"},
    {"title": "Shang-Chi and the Legend of the Ten Rings", "year": 2021, "genre": "Action, Adventure, Fantasy", "plot": "Shang-Chi, the master of unarmed weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization. A martial arts spectacle with deep family themes.", "imdb_rating": 7.4, "runtime": "132 min", "director": "Destin Daniel Cretton", "actors": "Simu Liu, Awkwafina, Tony Leung, Michelle Yeoh", "studio": "Marvel Studios", "franchise": "MCU", "franchise_order": 25, "imdb_id": "tt9376612"},
    {"title": "Eternals", "year": 2021, "genre": "Action, Adventure, Fantasy", "plot": "The Eternals, an immortal alien race, emerge from hiding after thousands of years to protect Earth from their evil counterparts, the Deviants. A sweeping epic with a diverse ensemble cast.", "imdb_rating": 6.3, "runtime": "156 min", "director": "Chloé Zhao", "actors": "Gemma Chan, Richard Madden, Angelina Jolie, Salma Hayek", "studio": "Marvel Studios", "franchise": "MCU", "franchise_order": 26, "imdb_id": "tt9032400"},

    # ── DC (8) ─────────────────────────────────────────────────────────────
    {"title": "The Dark Knight", "year": 2008, "genre": "Action, Crime, Drama", "plot": "When the menace known as the Joker wreaks havoc on Gotham, Batman must accept one of the greatest psychological tests of his ability to fight injustice. Heath Ledger's iconic performance.", "imdb_rating": 9.0, "runtime": "152 min", "director": "Christopher Nolan", "actors": "Christian Bale, Heath Ledger, Aaron Eckhart, Gary Oldman", "studio": "Warner Bros.", "franchise": "The Dark Knight Trilogy", "franchise_order": 2, "imdb_id": "tt0468569"},
    {"title": "The Dark Knight Rises", "year": 2012, "genre": "Action, Drama, Thriller", "plot": "Eight years after the Joker's reign of anarchy, Batman must return to protect Gotham from the brutal guerrilla terrorist Bane. An epic conclusion to Nolan's trilogy.", "imdb_rating": 8.4, "runtime": "164 min", "director": "Christopher Nolan", "actors": "Christian Bale, Tom Hardy, Anne Hathaway, Gary Oldman", "studio": "Warner Bros.", "franchise": "The Dark Knight Trilogy", "franchise_order": 3, "imdb_id": "tt1345836"},
    {"title": "Batman Begins", "year": 2005, "genre": "Action, Adventure, Drama", "plot": "After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption. Christopher Nolan reinvents the superhero genre with a grounded, realistic approach.", "imdb_rating": 8.2, "runtime": "140 min", "director": "Christopher Nolan", "actors": "Christian Bale, Michael Caine, Ken Watanabe, Liam Neeson", "studio": "Warner Bros.", "franchise": "The Dark Knight Trilogy", "franchise_order": 1, "imdb_id": "tt0372784"},
    {"title": "Wonder Woman", "year": 2017, "genre": "Action, Adventure, Fantasy", "plot": "When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior, leaves home to fight a war, discovering her full powers and true destiny along the way.", "imdb_rating": 7.4, "runtime": "141 min", "director": "Patty Jenkins", "actors": "Gal Gadot, Chris Pine, Robin Wright, Danny Huston", "studio": "Warner Bros.", "franchise": "DCEU", "franchise_order": 4, "imdb_id": "tt0451279"},
    {"title": "Aquaman", "year": 2018, "genre": "Action, Adventure, Fantasy", "plot": "Arthur Curry, the half-human, half-Atlantean heir to the underwater kingdom, must step forward to lead his people against his half-brother who seeks to unite ocean and surface dwellers in war.", "imdb_rating": 6.9, "runtime": "143 min", "director": "James Wan", "actors": "Jason Momoa, Amber Heard, Willem Dafoe, Patrick Wilson", "studio": "Warner Bros.", "franchise": "DCEU", "franchise_order": 6, "imdb_id": "tt1477834"},
    {"title": "Joker", "year": 2019, "genre": "Crime, Drama, Thriller", "plot": "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime in this character study.", "imdb_rating": 8.4, "runtime": "122 min", "director": "Todd Phillips", "actors": "Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy", "studio": "Warner Bros.", "franchise": None, "franchise_order": None, "imdb_id": "tt7286456"},
    {"title": "The Batman", "year": 2022, "genre": "Action, Crime, Drama", "plot": "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.", "imdb_rating": 7.8, "runtime": "176 min", "director": "Matt Reeves", "actors": "Robert Pattinson, Zoë Kravitz, Jeffrey Wright, Colin Farrell", "studio": "Warner Bros.", "franchise": None, "franchise_order": None, "imdb_id": "tt1877830"},
    {"title": "Man of Steel", "year": 2013, "genre": "Action, Adventure, Sci-Fi", "plot": "An alien child is evacuated from his dying world and sent to Earth. Growing up with superhuman abilities, he must decide how to use his powers when Earth is threatened by others of his kind.", "imdb_rating": 7.0, "runtime": "143 min", "director": "Zack Snyder", "actors": "Henry Cavill, Amy Adams, Michael Shannon, Russell Crowe", "studio": "Warner Bros.", "franchise": "DCEU", "franchise_order": 1, "imdb_id": "tt0770828"},

    # ── Star Wars (6) ──────────────────────────────────────────────────────
    {"title": "Star Wars: Episode IV - A New Hope", "year": 1977, "genre": "Action, Adventure, Fantasy", "plot": "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee, and two droids to save the galaxy from the Empire's Death Star. The film that started one of the biggest franchises ever.", "imdb_rating": 8.6, "runtime": "121 min", "director": "George Lucas", "actors": "Mark Hamill, Harrison Ford, Carrie Fisher, Alec Guinness", "studio": "Lucasfilm", "franchise": "Star Wars", "franchise_order": 1, "imdb_id": "tt0076759"},
    {"title": "Star Wars: Episode V - The Empire Strikes Back", "year": 1980, "genre": "Action, Adventure, Fantasy", "plot": "After the Rebels are brutally overpowered, Luke Skywalker begins Jedi training with Yoda, while friends are pursued by Darth Vader and bounty hunter Boba Fett. Often cited as the greatest sequel ever.", "imdb_rating": 8.7, "runtime": "124 min", "director": "Irvin Kershner", "actors": "Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams", "studio": "Lucasfilm", "franchise": "Star Wars", "franchise_order": 2, "imdb_id": "tt0080684"},
    {"title": "Star Wars: Episode VI - Return of the Jedi", "year": 1983, "genre": "Action, Adventure, Fantasy", "plot": "After a daring mission to rescue Han Solo from Jabba the Hutt, the Rebels dispatch to Endor to destroy the second Death Star. Luke confronts Vader in a final battle for the galaxy.", "imdb_rating": 8.3, "runtime": "131 min", "director": "Richard Marquand", "actors": "Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams", "studio": "Lucasfilm", "franchise": "Star Wars", "franchise_order": 3, "imdb_id": "tt0086190"},
    {"title": "Star Wars: The Force Awakens", "year": 2015, "genre": "Action, Adventure, Sci-Fi", "plot": "A new threat rises in the galaxy as the First Order seeks to destroy the New Republic. Rey, Finn, and Poe join forces with Han Solo and the Resistance to find the missing Luke Skywalker.", "imdb_rating": 7.8, "runtime": "138 min", "director": "J.J. Abrams", "actors": "Daisy Ridley, John Boyega, Oscar Isaac, Harrison Ford", "studio": "Lucasfilm", "franchise": "Star Wars", "franchise_order": 7, "imdb_id": "tt2488496"},
    {"title": "Rogue One: A Star Wars Story", "year": 2016, "genre": "Action, Adventure, Sci-Fi", "plot": "The Rebel Alliance makes a risky move to steal the plans for the Death Star, setting up the pivotal events of A New Hope. A gritty war film set in the Star Wars universe.", "imdb_rating": 7.8, "runtime": "133 min", "director": "Gareth Edwards", "actors": "Felicity Jones, Diego Luna, Ben Mendelsohn, Donnie Yen", "studio": "Lucasfilm", "franchise": "Star Wars", "franchise_order": 4, "imdb_id": "tt3748528"},
    {"title": "The Mandalorian", "year": 2019, "genre": "Action, Adventure, Sci-Fi", "plot": "A lone bounty hunter in the outer reaches of the galaxy discovers a mysterious young creature and becomes its unlikely protector. Set after the fall of the Empire, blending western and samurai genres.", "imdb_rating": 8.7, "runtime": "40 min", "director": "Jon Favreau", "actors": "Pedro Pascal, Carl Weathers, Giancarlo Esposito, Gina Carano", "studio": "Lucasfilm", "franchise": "Star Wars", "franchise_order": 10, "imdb_id": "tt8111088"},

    # ── Classic / Oscar Winners (20) ───────────────────────────────────────
    {"title": "The Shawshank Redemption", "year": 1994, "genre": "Drama", "plot": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency. Widely regarded as one of the greatest films ever made.", "imdb_rating": 9.3, "runtime": "142 min", "director": "Frank Darabont", "actors": "Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler", "studio": "Columbia Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt0111161"},
    {"title": "The Godfather", "year": 1972, "genre": "Crime, Drama", "plot": "The aging patriarch of an organized crime dynasty transfers control to his reluctant son. A landmark in American cinema exploring power, family loyalty, and the American Dream's dark side.", "imdb_rating": 9.2, "runtime": "175 min", "director": "Francis Ford Coppola", "actors": "Marlon Brando, Al Pacino, James Caan, Robert Duvall", "studio": "Paramount Pictures", "franchise": "The Godfather", "franchise_order": 1, "imdb_id": "tt0068646"},
    {"title": "Schindler's List", "year": 1993, "genre": "Biography, Drama, History", "plot": "In German-occupied Poland during World War II, industrialist Oskar Schindler becomes concerned for his Jewish workforce after witnessing the persecution of Jews. He saves over a thousand lives.", "imdb_rating": 9.0, "runtime": "195 min", "director": "Steven Spielberg", "actors": "Liam Neeson, Ralph Fiennes, Ben Kingsley, Caroline Goodall", "studio": "Universal Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt0108052"},
    {"title": "Forrest Gump", "year": 1994, "genre": "Drama, Romance", "plot": "The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man with a low IQ but good intentions. A beloved American classic.", "imdb_rating": 8.8, "runtime": "142 min", "director": "Robert Zemeckis", "actors": "Tom Hanks, Robin Wright, Gary Sinise, Sally Field", "studio": "Paramount Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt0109830"},
    {"title": "The Silence of the Lambs", "year": 1991, "genre": "Crime, Drama, Thriller", "plot": "A young FBI cadet must receive the help of an incarcerated and manipulative cannibalistic serial killer to catch another serial killer. Won all five major Academy Awards.", "imdb_rating": 8.6, "runtime": "118 min", "director": "Jonathan Demme", "actors": "Jodie Foster, Anthony Hopkins, Scott Glenn, Ted Levine", "studio": "Universal Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt0102926"},
    {"title": "Pulp Fiction", "year": 1994, "genre": "Crime, Drama", "plot": "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption. Tarantino's masterpiece that revolutionized independent cinema.", "imdb_rating": 8.9, "runtime": "154 min", "director": "Quentin Tarantino", "actors": "John Travolta, Uma Thurman, Samuel L. Jackson, Bruce Willis", "studio": "Lionsgate", "franchise": None, "franchise_order": None, "imdb_id": "tt0110912"},
    {"title": "Fight Club", "year": 1999, "genre": "Drama", "plot": "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more. A dark satirical commentary on consumer culture and identity.", "imdb_rating": 8.8, "runtime": "139 min", "director": "David Fincher", "actors": "Brad Pitt, Edward Norton, Meat Loaf, Zach Grenier", "studio": "20th Century Studios", "franchise": None, "franchise_order": None, "imdb_id": "tt0137523"},
    {"title": "The Matrix", "year": 1999, "genre": "Action, Sci-Fi", "plot": "A computer hacker learns that reality as he knows it is a simulation created by machines, and joins a rebellion to overthrow them. Revolutionized action cinema with bullet-time effects.", "imdb_rating": 8.7, "runtime": "136 min", "director": "Lana Wachowski, Lilly Wachowski", "actors": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving", "studio": "Warner Bros.", "franchise": "The Matrix", "franchise_order": 1, "imdb_id": "tt0133093"},
    {"title": "Goodfellas", "year": 1990, "genre": "Biography, Crime, Drama", "plot": "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeViso. Scorsese's masterful crime saga.", "imdb_rating": 8.7, "runtime": "146 min", "director": "Martin Scorsese", "actors": "Robert De Niro, Ray Liotta, Joe Pesci, Lorraine Bracco", "studio": "Warner Bros.", "franchise": None, "franchise_order": None, "imdb_id": "tt0099685"},
    {"title": "The Green Mile", "year": 1999, "genre": "Crime, Drama, Fantasy", "plot": "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift. A deeply moving adaptation of Stephen King's novel.", "imdb_rating": 8.6, "runtime": "189 min", "director": "Frank Darabont", "actors": "Tom Hanks, Michael Clarke Duncan, David Morse, Sam Rockwell", "studio": "Warner Bros.", "franchise": None, "franchise_order": None, "imdb_id": "tt0120689"},
    {"title": "Saving Private Ryan", "year": 1998, "genre": "Drama, War", "plot": "Following the Normandy landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action. Features one of cinema's greatest opening sequences.", "imdb_rating": 8.6, "runtime": "169 min", "director": "Steven Spielberg", "actors": "Tom Hanks, Matt Damon, Tom Sizemore, Edward Burns", "studio": "Paramount Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt0120815"},
    {"title": "Gladiator", "year": 2000, "genre": "Action, Adventure, Drama", "plot": "A former Roman general sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery. Ridley Scott's epic revival of the swords-and-sandals genre.", "imdb_rating": 8.5, "runtime": "155 min", "director": "Ridley Scott", "actors": "Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed", "studio": "Universal Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt0172495"},
    {"title": "A Beautiful Mind", "year": 2001, "genre": "Biography, Drama", "plot": "After John Nash, a brilliant mathematical genius, accepts secret Cold War work in cryptography, his life takes a turn for the nightmarish. A powerful portrayal of mental illness and genius.", "imdb_rating": 8.2, "runtime": "135 min", "director": "Ron Howard", "actors": "Russell Crowe, Ed Harris, Jennifer Connelly, Paul Bettany", "studio": "Universal Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt0268978"},
    {"title": "The Departed", "year": 2006, "genre": "Crime, Drama, Thriller", "plot": "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston. Scorsese's Oscar-winning remake of Infernal Affairs.", "imdb_rating": 8.5, "runtime": "151 min", "director": "Martin Scorsese", "actors": "Leonardo DiCaprio, Matt Damon, Jack Nicholson, Mark Wahlberg", "studio": "Warner Bros.", "franchise": None, "franchise_order": None, "imdb_id": "tt0407887"},
    {"title": "No Country for Old Men", "year": 2007, "genre": "Crime, Drama, Thriller", "plot": "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande. A tense, philosophical modern western.", "imdb_rating": 8.2, "runtime": "122 min", "director": "Ethan Coen, Joel Coen", "actors": "Tommy Lee Jones, Javier Bardem, Josh Brolin, Woody Harrelson", "studio": "Paramount Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt0477348"},
    {"title": "There Will Be Blood", "year": 2007, "genre": "Drama", "plot": "A story of family, religion, hatred, oil, and madness, focusing on a turn-of-the-century prospector in the early days of the business. Daniel Day-Lewis delivers a towering performance.", "imdb_rating": 8.2, "runtime": "158 min", "director": "Paul Thomas Anderson", "actors": "Daniel Day-Lewis, Paul Dano, Ciarán Hinds, Kevin J. O'Connor", "studio": "Paramount Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt0469494"},
    {"title": "The Social Network", "year": 2010, "genre": "Biography, Drama", "plot": "As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea. A sharp modern drama.", "imdb_rating": 7.8, "runtime": "120 min", "director": "David Fincher", "actors": "Jesse Eisenberg, Andrew Garfield, Justin Timberlake, Armie Hammer", "studio": "Columbia Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt1285016"},
    {"title": "12 Years a Slave", "year": 2013, "genre": "Biography, Drama, History", "plot": "In the antebellum United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery. Based on an incredible true story of resilience and survival.", "imdb_rating": 8.1, "runtime": "134 min", "director": "Steve McQueen", "actors": "Chiwetel Ejiofor, Michael Fassbender, Lupita Nyong'o, Benedict Cumberbatch", "studio": "20th Century Studios", "franchise": None, "franchise_order": None, "imdb_id": "tt2024544"},
    {"title": "Whiplash", "year": 2014, "genre": "Drama, Music", "plot": "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.", "imdb_rating": 8.5, "runtime": "106 min", "director": "Damien Chazelle", "actors": "Miles Teller, J.K. Simmons, Paul Reiser, Melissa Benoist", "studio": "Columbia Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt2582802"},
    {"title": "Moonlight", "year": 2016, "genre": "Drama", "plot": "A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood. A Best Picture winner.", "imdb_rating": 7.4, "runtime": "111 min", "director": "Barry Jenkins", "actors": "Mahershala Ali, Naomie Harris, Trevante Rhodes, André Holland", "studio": "A24", "franchise": None, "franchise_order": None, "imdb_id": "tt4975722"},

    # ── Sci-Fi / Fantasy (12) ──────────────────────────────────────────────
    {"title": "Inception", "year": 2010, "genre": "Action, Adventure, Sci-Fi", "plot": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O. A mind-bending masterpiece.", "imdb_rating": 8.8, "runtime": "148 min", "director": "Christopher Nolan", "actors": "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy", "studio": "Warner Bros.", "franchise": None, "franchise_order": None, "imdb_id": "tt1375666"},
    {"title": "Interstellar", "year": 2014, "genre": "Adventure, Drama, Sci-Fi", "plot": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival as Earth faces environmental catastrophe. A visually stunning exploration of love and physics.", "imdb_rating": 8.7, "runtime": "169 min", "director": "Christopher Nolan", "actors": "Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine", "studio": "Paramount Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt0816692"},
    {"title": "Blade Runner 2049", "year": 2017, "genre": "Action, Drama, Mystery, Sci-Fi", "plot": "Young blade runner K's discovery of a long-buried secret leads him to track down former blade runner Rick Deckard. A visually breathtaking sequel that expands the original's philosophical questions.", "imdb_rating": 8.0, "runtime": "164 min", "director": "Denis Villeneuve", "actors": "Ryan Gosling, Harrison Ford, Ana de Armas, Jared Leto", "studio": "Warner Bros.", "franchise": "Blade Runner", "franchise_order": 2, "imdb_id": "tt1856101"},
    {"title": "Arrival", "year": 2016, "genre": "Drama, Mystery, Sci-Fi", "plot": "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world. A deeply emotional first-contact story about language and time.", "imdb_rating": 7.9, "runtime": "116 min", "director": "Denis Villeneuve", "actors": "Amy Adams, Jeremy Renner, Forest Whitaker, Michael Stuhlbarg", "studio": "Paramount Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt2543164"},
    {"title": "The Lord of the Rings: The Fellowship of the Ring", "year": 2001, "genre": "Action, Adventure, Drama, Fantasy", "plot": "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron. The beginning of an epic trilogy.", "imdb_rating": 8.9, "runtime": "178 min", "director": "Peter Jackson", "actors": "Elijah Wood, Ian McKellen, Orlando Bloom, Sean Bean", "studio": "New Line Cinema", "franchise": "The Lord of the Rings", "franchise_order": 1, "imdb_id": "tt0120737"},
    {"title": "The Lord of the Rings: The Two Towers", "year": 2002, "genre": "Action, Adventure, Drama, Fantasy", "plot": "While Frodo and Sam continue toward Mordor with Gollum, Aragorn, Legolas and Gimli pursue the Uruk-hai that captured Merry and Pippin. The Battle of Helm's Deep is one of cinema's greatest battles.", "imdb_rating": 8.8, "runtime": "179 min", "director": "Peter Jackson", "actors": "Elijah Wood, Ian McKellen, Viggo Mortensen, Andy Serkis", "studio": "New Line Cinema", "franchise": "The Lord of the Rings", "franchise_order": 2, "imdb_id": "tt0167261"},
    {"title": "The Lord of the Rings: The Return of the King", "year": 2003, "genre": "Action, Adventure, Drama, Fantasy", "plot": "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring. Won 11 Academy Awards including Best Picture.", "imdb_rating": 9.0, "runtime": "201 min", "director": "Peter Jackson", "actors": "Elijah Wood, Viggo Mortensen, Ian McKellen, Sean Astin", "studio": "New Line Cinema", "franchise": "The Lord of the Rings", "franchise_order": 3, "imdb_id": "tt0167260"},
    {"title": "Dune", "year": 2021, "genre": "Action, Adventure, Drama, Sci-Fi", "plot": "Paul Atreides, a brilliant and gifted young man born into a great destiny, must travel to the most dangerous planet in the universe to ensure the future of his family and his people.", "imdb_rating": 8.0, "runtime": "155 min", "director": "Denis Villeneuve", "actors": "Timothée Chalamet, Rebecca Ferguson, Zendaya, Oscar Isaac", "studio": "Warner Bros.", "franchise": "Dune", "franchise_order": 1, "imdb_id": "tt1160419"},
    {"title": "Avatar", "year": 2009, "genre": "Action, Adventure, Fantasy, Sci-Fi", "plot": "A paraplegic Marine dispatched to Pandora on a unique mission becomes torn between following orders and protecting the world he feels is his home. The highest-grossing film of its time.", "imdb_rating": 7.9, "runtime": "162 min", "director": "James Cameron", "actors": "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang", "studio": "20th Century Studios", "franchise": "Avatar", "franchise_order": 1, "imdb_id": "tt0499549"},
    {"title": "The Terminator", "year": 1984, "genre": "Action, Sci-Fi", "plot": "A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine sent from the same year to kill a young woman whose unborn son is the key to humanity's future.", "imdb_rating": 8.1, "runtime": "107 min", "director": "James Cameron", "actors": "Arnold Schwarzenegger, Linda Hamilton, Michael Biehn, Paul Winfield", "studio": "Universal Pictures", "franchise": "Terminator", "franchise_order": 1, "imdb_id": "tt0088247"},
    {"title": "Alien", "year": 1979, "genre": "Horror, Sci-Fi", "plot": "The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission. Ridley Scott created one of cinema's most terrifying and enduring monsters.", "imdb_rating": 8.5, "runtime": "117 min", "director": "Ridley Scott", "actors": "Sigourney Weaver, Tom Skerritt, John Hurt, Veronica Cartwright", "studio": "20th Century Studios", "franchise": "Alien", "franchise_order": 1, "imdb_id": "tt0078748"},
    {"title": "Jurassic Park", "year": 1993, "genre": "Action, Adventure, Sci-Fi", "plot": "A pragmatic paleontologist touring an almost complete theme park on an island is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.", "imdb_rating": 8.2, "runtime": "127 min", "director": "Steven Spielberg", "actors": "Sam Neill, Laura Dern, Jeff Goldblum, Richard Attenborough", "studio": "Universal Pictures", "franchise": "Jurassic Park", "franchise_order": 1, "imdb_id": "tt0107290"},

    # ── Animation (10) ────────────────────────────────────────────────────
    {"title": "Spirited Away", "year": 2001, "genre": "Animation, Adventure, Family", "plot": "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits. She must find courage to free herself and her parents. Miyazaki's masterpiece.", "imdb_rating": 8.6, "runtime": "125 min", "director": "Hayao Miyazaki", "actors": "Daveigh Chase, Suzanne Pleshette, Miyu Irino, Rumi Hiiragi", "studio": "Studio Ghibli", "franchise": None, "franchise_order": None, "imdb_id": "tt0245429"},
    {"title": "Your Name", "year": 2016, "genre": "Animation, Drama, Fantasy, Romance", "plot": "Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart? A beautifully animated tale of fate and longing.", "imdb_rating": 8.4, "runtime": "106 min", "director": "Makoto Shinkai", "actors": "Ryunosuke Kamiki, Mone Kamishiraishi, Ryô Narita, Aoi Yūki", "studio": "Toho", "franchise": None, "franchise_order": None, "imdb_id": "tt5311514"},
    {"title": "Spider-Man: Into the Spider-Verse", "year": 2018, "genre": "Animation, Action, Adventure", "plot": "Teen Miles Morales becomes the Spider-Man of his universe. When he crosses paths with counterparts from other dimensions, they must band together to stop a threat to all realities.", "imdb_rating": 8.4, "runtime": "117 min", "director": "Bob Persichetti, Peter Ramsey, Rodney Rothman", "actors": "Shameik Moore, Jake Johnson, Hailee Steinfeld, Mahershala Ali", "studio": "Columbia Pictures", "franchise": "Spider-Verse", "franchise_order": 1, "imdb_id": "tt4633694"},
    {"title": "Toy Story", "year": 1995, "genre": "Animation, Adventure, Comedy, Family", "plot": "A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy's room. The first feature-length computer-animated film ever made.", "imdb_rating": 8.3, "runtime": "81 min", "director": "John Lasseter", "actors": "Tom Hanks, Tim Allen, Don Rickles, Jim Varney", "studio": "Pixar", "franchise": "Toy Story", "franchise_order": 1, "imdb_id": "tt0114709"},
    {"title": "Finding Nemo", "year": 2003, "genre": "Animation, Adventure, Comedy, Family", "plot": "After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home. A heartwarming underwater adventure.", "imdb_rating": 8.2, "runtime": "100 min", "director": "Andrew Stanton", "actors": "Albert Brooks, Ellen DeGeneres, Alexander Gould, Willem Dafoe", "studio": "Pixar", "franchise": None, "franchise_order": None, "imdb_id": "tt0266543"},
    {"title": "Up", "year": 2009, "genre": "Animation, Adventure, Comedy, Family", "plot": "78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young wilderness explorer along. A deeply emotional story about love and adventure.", "imdb_rating": 8.3, "runtime": "96 min", "director": "Pete Docter", "actors": "Edward Asner, Jordan Nagai, John Ratzenberger, Christopher Plummer", "studio": "Pixar", "franchise": None, "franchise_order": None, "imdb_id": "tt1049413"},
    {"title": "Coco", "year": 2017, "genre": "Animation, Adventure, Drama, Family, Fantasy, Music", "plot": "Aspiring musician Miguel enters the stunning and colorful Land of the Dead to unlock the real story behind his family history. A beautiful celebration of Mexican culture and family bonds.", "imdb_rating": 8.4, "runtime": "105 min", "director": "Lee Unkrich", "actors": "Anthony Gonzalez, Gael García Bernal, Benjamin Bratt, Alanna Ubach", "studio": "Pixar", "franchise": None, "franchise_order": None, "imdb_id": "tt2380307"},
    {"title": "The Lion King", "year": 1994, "genre": "Animation, Adventure, Drama, Family, Musical", "plot": "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself. After tragedy strikes, Simba must reclaim his rightful place as king.", "imdb_rating": 8.5, "runtime": "88 min", "director": "Roger Allers, Rob Minkoff", "actors": "Matthew Broderick, Jeremy Irons, James Earl Jones, Moira Kelly", "studio": "Walt Disney Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt0110357"},
    {"title": "WALL-E", "year": 2008, "genre": "Animation, Adventure, Family, Sci-Fi", "plot": "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind. A touching love story told mostly without dialogue.", "imdb_rating": 8.4, "runtime": "98 min", "director": "Andrew Stanton", "actors": "Ben Burtt, Elissa Knight, Jeff Garlin, Fred Willard", "studio": "Pixar", "franchise": None, "franchise_order": None, "imdb_id": "tt0910970"},
    {"title": "Ratatouille", "year": 2007, "genre": "Animation, Adventure, Comedy, Family, Fantasy", "plot": "A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant. Pixar's love letter to food, art, and following your dreams.", "imdb_rating": 8.1, "runtime": "111 min", "director": "Brad Bird", "actors": "Patton Oswalt, Ian Holm, Lou Romano, Brian Dennehy", "studio": "Pixar", "franchise": None, "franchise_order": None, "imdb_id": "tt0382932"},

    # ── Horror / Thriller (8) ─────────────────────────────────────────────
    {"title": "Get Out", "year": 2017, "genre": "Horror, Mystery, Thriller", "plot": "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point. A genre-defining social thriller.", "imdb_rating": 7.7, "runtime": "104 min", "director": "Jordan Peele", "actors": "Daniel Kaluuya, Allison Williams, Bradley Whitford, Catherine Keener", "studio": "Universal Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt5052448"},
    {"title": "A Quiet Place", "year": 2018, "genre": "Drama, Horror, Sci-Fi", "plot": "In a post-apocalyptic world, a family is forced to live in silence while hiding from creatures that hunt by sound. An intense survival horror that innovates with its near-silent storytelling.", "imdb_rating": 7.5, "runtime": "90 min", "director": "John Krasinski", "actors": "Emily Blunt, John Krasinski, Millicent Simmonds, Noah Jupe", "studio": "Paramount Pictures", "franchise": "A Quiet Place", "franchise_order": 1, "imdb_id": "tt6644200"},
    {"title": "Hereditary", "year": 2018, "genre": "Drama, Horror, Mystery", "plot": "A grieving family is haunted by tragic and disturbing occurrences after the death of their secretive grandmother. Ari Aster's terrifying debut that redefines modern horror.", "imdb_rating": 7.3, "runtime": "127 min", "director": "Ari Aster", "actors": "Toni Collette, Milly Shapiro, Gabriel Byrne, Alex Wolff", "studio": "A24", "franchise": None, "franchise_order": None, "imdb_id": "tt7784604"},
    {"title": "The Shining", "year": 1980, "genre": "Drama, Horror", "plot": "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings. Kubrick's masterful horror classic.", "imdb_rating": 8.4, "runtime": "146 min", "director": "Stanley Kubrick", "actors": "Jack Nicholson, Shelley Duvall, Danny Lloyd, Scatman Crothers", "studio": "Warner Bros.", "franchise": None, "franchise_order": None, "imdb_id": "tt0081505"},
    {"title": "Parasite", "year": 2019, "genre": "Comedy, Drama, Thriller", "plot": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan. The first non-English film to win Best Picture.", "imdb_rating": 8.5, "runtime": "132 min", "director": "Bong Joon Ho", "actors": "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik", "studio": "Toho", "franchise": None, "franchise_order": None, "imdb_id": "tt6751668"},
    {"title": "Gone Girl", "year": 2014, "genre": "Drama, Mystery, Thriller", "plot": "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent. A twisted modern thriller.", "imdb_rating": 8.1, "runtime": "149 min", "director": "David Fincher", "actors": "Ben Affleck, Rosamund Pike, Neil Patrick Harris, Tyler Perry", "studio": "20th Century Studios", "franchise": None, "franchise_order": None, "imdb_id": "tt2267998"},
    {"title": "Se7en", "year": 1995, "genre": "Crime, Drama, Mystery, Thriller", "plot": "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives. Fincher's dark masterpiece with one of cinema's most shocking endings.", "imdb_rating": 8.6, "runtime": "127 min", "director": "David Fincher", "actors": "Morgan Freeman, Brad Pitt, Kevin Spacey, Gwyneth Paltrow", "studio": "New Line Cinema", "franchise": None, "franchise_order": None, "imdb_id": "tt0114369"},
    {"title": "The Conjuring", "year": 2013, "genre": "Horror, Mystery, Thriller", "plot": "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse. James Wan delivers one of the best haunted house films in decades.", "imdb_rating": 7.5, "runtime": "112 min", "director": "James Wan", "actors": "Vera Farmiga, Patrick Wilson, Lili Taylor, Ron Livingston", "studio": "Warner Bros.", "franchise": "The Conjuring Universe", "franchise_order": 1, "imdb_id": "tt1457767"},

    # ── Comedy (8) ────────────────────────────────────────────────────────
    {"title": "The Grand Budapest Hotel", "year": 2014, "genre": "Adventure, Comedy, Crime", "plot": "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy under the legendary concierge. Wes Anderson's whimsical masterwork.", "imdb_rating": 8.1, "runtime": "99 min", "director": "Wes Anderson", "actors": "Ralph Fiennes, F. Murray Abraham, Mathieu Amalric, Adrien Brody", "studio": "20th Century Studios", "franchise": None, "franchise_order": None, "imdb_id": "tt2278388"},
    {"title": "Superbad", "year": 2007, "genre": "Comedy", "plot": "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry. A raunchy, heart-filled coming-of-age comedy.", "imdb_rating": 7.6, "runtime": "113 min", "director": "Greg Mottola", "actors": "Jonah Hill, Michael Cera, Christopher Mintz-Plasse, Bill Hader", "studio": "Columbia Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt0829482"},
    {"title": "The Hangover", "year": 2009, "genre": "Comedy", "plot": "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They must retrace their steps to find him before the wedding.", "imdb_rating": 7.7, "runtime": "100 min", "director": "Todd Phillips", "actors": "Zach Galifianakis, Bradley Cooper, Justin Bartha, Ed Helms", "studio": "Warner Bros.", "franchise": "The Hangover", "franchise_order": 1, "imdb_id": "tt1119646"},
    {"title": "Bridesmaids", "year": 2011, "genre": "Comedy, Romance", "plot": "Competition between the maid of honor and a bridesmaid, over who is the bride's best friend, threatens to upend the life of an idealistic woman. A hilarious and surprisingly touching comedy.", "imdb_rating": 6.8, "runtime": "125 min", "director": "Paul Feig", "actors": "Kristen Wiig, Maya Rudolph, Rose Byrne, Melissa McCarthy", "studio": "Universal Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt1478338"},
    {"title": "Step Brothers", "year": 2008, "genre": "Comedy", "plot": "Two aimless middle-aged losers still living at home are forced against their will to become roommates when their parents marry. Will Ferrell and John C. Reilly deliver outrageous comedic chemistry.", "imdb_rating": 6.9, "runtime": "98 min", "director": "Adam McKay", "actors": "Will Ferrell, John C. Reilly, Mary Steenburgen, Richard Jenkins", "studio": "Columbia Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt0838283"},
    {"title": "Knives Out", "year": 2019, "genre": "Comedy, Crime, Drama, Mystery", "plot": "A detective investigates the death of a patriarch of an eccentric, combative family. Rian Johnson crafts a delightfully twisty whodunit for the modern era.", "imdb_rating": 7.9, "runtime": "130 min", "director": "Rian Johnson", "actors": "Daniel Craig, Chris Evans, Ana de Armas, Jamie Lee Curtis", "studio": "Lionsgate", "franchise": "Knives Out", "franchise_order": 1, "imdb_id": "tt8946378"},
    {"title": "The Big Lebowski", "year": 1998, "genre": "Comedy, Crime", "plot": "Ultimate LA slacker Jeffrey 'The Dude' Lebowski is mistaken for a millionaire of the same name and is drawn into a bizarre kidnapping caper. A Coen Brothers cult classic.", "imdb_rating": 8.1, "runtime": "117 min", "director": "Joel Coen, Ethan Coen", "actors": "Jeff Bridges, John Goodman, Julianne Moore, Steve Buscemi", "studio": "Universal Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt0118715"},
    {"title": "Groundhog Day", "year": 1993, "genre": "Comedy, Drama, Fantasy, Romance", "plot": "A weatherman finds himself inexplicably living the same day over and over again. Gradually he begins to re-examine his life and priorities. Bill Murray at his finest.", "imdb_rating": 8.1, "runtime": "101 min", "director": "Harold Ramis", "actors": "Bill Murray, Andie MacDowell, Chris Elliott, Stephen Tobolowsky", "studio": "Columbia Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt0107048"},

    # ── Action (8) ────────────────────────────────────────────────────────
    {"title": "John Wick", "year": 2014, "genre": "Action, Crime, Thriller", "plot": "An ex-hitman comes out of retirement to track down the gangsters that killed his dog and took everything from him. Keanu Reeves delivers relentless, stylish action.", "imdb_rating": 7.4, "runtime": "101 min", "director": "Chad Stahelski", "actors": "Keanu Reeves, Michael Nyqvist, Alfie Allen, Willem Dafoe", "studio": "Lionsgate", "franchise": "John Wick", "franchise_order": 1, "imdb_id": "tt2911666"},
    {"title": "Mad Max: Fury Road", "year": 2015, "genre": "Action, Adventure, Sci-Fi", "plot": "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the aid of a group of female prisoners and a drifter named Max. A relentless action masterpiece.", "imdb_rating": 8.1, "runtime": "120 min", "director": "George Miller", "actors": "Tom Hardy, Charlize Theron, Nicholas Hoult, Hugh Keays-Byrne", "studio": "Warner Bros.", "franchise": "Mad Max", "franchise_order": 4, "imdb_id": "tt1392190"},
    {"title": "Die Hard", "year": 1988, "genre": "Action, Thriller", "plot": "An NYPD officer tries to save his wife and several others taken hostage by German terrorists during a Christmas party at the Nakatomi Plaza. The gold standard of action filmmaking.", "imdb_rating": 8.2, "runtime": "132 min", "director": "John McTiernan", "actors": "Bruce Willis, Alan Rickman, Bonnie Bedelia, Reginald VelJohnson", "studio": "20th Century Studios", "franchise": "Die Hard", "franchise_order": 1, "imdb_id": "tt0095016"},
    {"title": "Top Gun: Maverick", "year": 2022, "genre": "Action, Drama", "plot": "After more than thirty years of service, Navy aviator Pete 'Maverick' Mitchell is where he belongs, pushing the envelope as a courageous test pilot. A legacy sequel done perfectly right.", "imdb_rating": 8.2, "runtime": "130 min", "director": "Joseph Kosinski", "actors": "Tom Cruise, Jennifer Connelly, Miles Teller, Val Kilmer", "studio": "Paramount Pictures", "franchise": "Top Gun", "franchise_order": 2, "imdb_id": "tt1745960"},
    {"title": "Mission: Impossible - Fallout", "year": 2018, "genre": "Action, Adventure, Thriller", "plot": "Ethan Hunt and his IMF team race against time after a mission gone wrong. The best entry in the franchise, featuring jaw-dropping practical stunts including a HALO jump.", "imdb_rating": 7.7, "runtime": "147 min", "director": "Christopher McQuarrie", "actors": "Tom Cruise, Henry Cavill, Ving Rhames, Simon Pegg", "studio": "Paramount Pictures", "franchise": "Mission: Impossible", "franchise_order": 6, "imdb_id": "tt4912910"},
    {"title": "The Raid", "year": 2011, "genre": "Action, Thriller", "plot": "A SWAT team becomes trapped in a tenement run by a ruthless mobster and his army of killers and thugs. Relentless Indonesian martial arts action that redefined the genre.", "imdb_rating": 7.6, "runtime": "101 min", "director": "Gareth Evans", "actors": "Iko Uwais, Ananda George, Ray Sahetapy, Joe Taslim", "studio": "Columbia Pictures", "franchise": "The Raid", "franchise_order": 1, "imdb_id": "tt1899353"},
    {"title": "Kill Bill: Volume 1", "year": 2003, "genre": "Action, Crime, Drama, Thriller", "plot": "After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her. Tarantino's stylish homage to martial arts cinema.", "imdb_rating": 8.2, "runtime": "111 min", "director": "Quentin Tarantino", "actors": "Uma Thurman, David Carradine, Daryl Hannah, Lucy Liu", "studio": "Lionsgate", "franchise": "Kill Bill", "franchise_order": 1, "imdb_id": "tt0266697"},
    {"title": "Baby Driver", "year": 2017, "genre": "Action, Crime, Drama, Music, Thriller", "plot": "After being coerced into working for a crime boss, a young getaway driver finds himself taking part in a heist doomed to fail. Edgar Wright's musical action masterpiece.", "imdb_rating": 7.6, "runtime": "113 min", "director": "Edgar Wright", "actors": "Ansel Elgort, Kevin Spacey, Lily James, Jon Hamm", "studio": "Columbia Pictures", "franchise": None, "franchise_order": None, "imdb_id": "tt3890160"},

    # ── Japanese / Toho (5) ───────────────────────────────────────────────
    {"title": "Godzilla", "year": 1954, "genre": "Horror, Sci-Fi", "plot": "American nuclear weapons testing results in the creation of a seemingly unstoppable dinosaur-like beast. The original kaiju film that launched a global franchise and became a cultural icon.", "imdb_rating": 7.5, "runtime": "96 min", "director": "Ishirō Honda", "actors": "Takashi Shimura, Akihiko Hirata, Akira Takarada, Momoko Kōchi", "studio": "Toho", "franchise": "Godzilla", "franchise_order": 1, "imdb_id": "tt0047034"},
    {"title": "Seven Samurai", "year": 1954, "genre": "Action, Drama", "plot": "A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves. Akira Kurosawa's epic that influenced countless westerns and action films.", "imdb_rating": 8.6, "runtime": "207 min", "director": "Akira Kurosawa", "actors": "Toshiro Mifune, Takashi Shimura, Keiko Tsushima, Yukiko Shimazaki", "studio": "Toho", "franchise": None, "franchise_order": None, "imdb_id": "tt0047478"},
    {"title": "Akira", "year": 1988, "genre": "Animation, Action, Drama, Fantasy, Sci-Fi", "plot": "A secret military project endangers Neo-Tokyo when it turns a biker gang member into a rampaging psychic psychopath. The landmark cyberpunk anime that changed animation worldwide.", "imdb_rating": 8.0, "runtime": "124 min", "director": "Katsuhiro Ôtomo", "actors": "Mitsuo Iwata, Nozomu Sasaki, Mami Koyama, Tessho Genda", "studio": "Toho", "franchise": None, "franchise_order": None, "imdb_id": "tt0094625"},
    {"title": "Princess Mononoke", "year": 1997, "genre": "Animation, Action, Adventure, Fantasy", "plot": "On a journey to find the cure for a Tatarigami's curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony. Miyazaki's environmental epic.", "imdb_rating": 8.4, "runtime": "134 min", "director": "Hayao Miyazaki", "actors": "Yōji Matsuda, Yuriko Ishida, Yūko Tanaka, Billy Crudup", "studio": "Studio Ghibli", "franchise": None, "franchise_order": None, "imdb_id": "tt0119698"},
    {"title": "Shin Godzilla", "year": 2016, "genre": "Action, Adventure, Drama, Horror, Sci-Fi", "plot": "Japan is plunged into chaos upon the appearance of a giant monster. The government scrambles to save the population while grappling with bureaucracy. A sharp political satire disguised as a monster film.", "imdb_rating": 6.8, "runtime": "120 min", "director": "Hideaki Anno, Shinji Higuchi", "actors": "Hiroki Hasegawa, Yutaka Takenouchi, Satomi Ishihara, Ren Osugi", "studio": "Toho", "franchise": "Godzilla", "franchise_order": 29, "imdb_id": "tt4262980"},

    # ── A24 Films (5) ─────────────────────────────────────────────────────
    {"title": "Everything Everywhere All at Once", "year": 2022, "genre": "Action, Adventure, Comedy, Fantasy, Sci-Fi", "plot": "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.", "imdb_rating": 7.8, "runtime": "139 min", "director": "Daniel Kwan, Daniel Scheinert", "actors": "Michelle Yeoh, Stephanie Hsu, Ke Huy Quan, Jamie Lee Curtis", "studio": "A24", "franchise": None, "franchise_order": None, "imdb_id": "tt6710474"},
    {"title": "Lady Bird", "year": 2017, "genre": "Comedy, Drama", "plot": "In 2002, an idealistic, artistic Sacramento teenager navigates her way through a loving but turbulent relationship with her strong-willed mother. Greta Gerwig's acclaimed directorial debut.", "imdb_rating": 7.4, "runtime": "94 min", "director": "Greta Gerwig", "actors": "Saoirse Ronan, Laurie Metcalf, Tracy Letts, Lucas Hedges", "studio": "A24", "franchise": None, "franchise_order": None, "imdb_id": "tt4925292"},
    {"title": "Midsommar", "year": 2019, "genre": "Drama, Horror, Mystery", "plot": "A couple travels to Northern Europe to visit a rural hometown's fabled Swedish mid-summer festival, but what begins as an idyllic retreat quickly devolves into an increasingly violent and bizarre competition.", "imdb_rating": 7.1, "runtime": "148 min", "director": "Ari Aster", "actors": "Florence Pugh, Jack Reynor, Vilhelm Blomgren, William Jackson Harper", "studio": "A24", "franchise": None, "franchise_order": None, "imdb_id": "tt8772262"},
    {"title": "The Lighthouse", "year": 2019, "genre": "Drama, Fantasy, Horror, Mystery, Thriller", "plot": "Two lighthouse keepers try to maintain their sanity while living on a remote and mysterious New England island in the 1890s. Robert Eggers' hypnotic, claustrophobic black-and-white descent into madness.", "imdb_rating": 7.4, "runtime": "109 min", "director": "Robert Eggers", "actors": "Robert Pattinson, Willem Dafoe, Valeriia Karaman, Logan Hawkes", "studio": "A24", "franchise": None, "franchise_order": None, "imdb_id": "tt7984734"},
    {"title": "Uncut Gems", "year": 2019, "genre": "Crime, Drama, Thriller", "plot": "A charismatic New York City jeweler makes a series of high-stakes bets that could lead to the windfall of a lifetime. The Safdie Brothers deliver an anxiety-inducing masterpiece.", "imdb_rating": 7.4, "runtime": "135 min", "director": "Benny Safdie, Josh Safdie", "actors": "Adam Sandler, Julia Fox, Kevin Garnett, Idina Menzel", "studio": "A24", "franchise": None, "franchise_order": None, "imdb_id": "tt5727208"},
]


def seed_database(db: Session) -> None:
    """Populate the database with studios, movies, and a demo user."""

    # ── Studios ────────────────────────────────────────────────────────────
    for studio_data in STUDIOS:
        existing = db.query(Studio).filter(Studio.name == studio_data["name"]).first()
        if not existing:
            db.add(Studio(**studio_data))

    db.commit()

    # ── Movies ─────────────────────────────────────────────────────────────
    for movie_data in MOVIES:
        data = dict(movie_data)
        # Generate poster URL from title
        data["poster_url"] = _poster(data["title"])

        existing = db.query(Movie).filter(Movie.title == data["title"]).first()
        if not existing:
            db.add(Movie(**data))

    db.commit()

    # ── Demo user ──────────────────────────────────────────────────────────
    existing_user = db.query(User).filter(User.username == "demo").first()
    if not existing_user:
        demo_user = User(
            username="demo",
            email="demo@example.com",
            hashed_password=get_password_hash("demo123"),
        )
        db.add(demo_user)
        db.commit()


if __name__ == "__main__":
    import sys
    import os

    # Ensure the project root is on the path
    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if project_root not in sys.path:
        sys.path.insert(0, project_root)

    from backend.database import SessionLocal, create_tables

    print("Creating tables...")
    create_tables()

    print("Seeding database...")
    session = SessionLocal()
    try:
        seed_database(session)
        print(f"Done! Seeded {len(MOVIES)} movies, {len(STUDIOS)} studios, and 1 demo user.")
    finally:
        session.close()
